# Generated by Django 3.1.3 on 2020-11-25 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('CRegistration_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=40)),
                ('Cgender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=40)),
                ('Cdept', models.CharField(choices=[('COMPUTER SCIENCE', 'COMPUTER SCIENCE'), ('INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY'), ('ELECTRONICS', 'ELECTRONICS'), ('MECHANICAL', 'MECHANICAL'), ('ELECTRICAL', 'ELECTRICAL')], max_length=40, null=True)),
                ('Cyear', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('Cusername', models.CharField(max_length=40)),
                ('Cpassword', models.CharField(max_length=40)),
                ('Cmobile_no', models.PositiveBigIntegerField()),
                ('Cemail_id', models.EmailField(max_length=254)),
                ('Cposition', models.CharField(choices=[('SECRETARY', 'SECRETARY'), ('ASSISTANT SECRETARY', 'ASSISTANT SECRETARY'), ('PRESIDENT', 'PRESIDENT'), ('VICE PRESIDENT', 'VICE PRESIDENT')], max_length=40)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('e_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('e_position', models.CharField(choices=[('SECRETARY', 'SECRETARY'), ('ASSISTANT SECRETARY', 'ASSISTANT SECRETARY'), ('PRESIDENT', 'PRESIDENT'), ('VICE PRESIDENT', 'VICE PRESIDENT')], max_length=40)),
                ('e_title', models.CharField(max_length=100)),
                ('e_date', models.DateField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('VRegistration_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Vname', models.CharField(max_length=40)),
                ('Vgender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=40)),
                ('Vdept', models.CharField(choices=[('COMPUTER SCIENCE', 'COMPUTER SCIENCE'), ('INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY'), ('ELECTRONICS', 'ELECTRONICS'), ('MECHANICAL', 'MECHANICAL'), ('ELECTRICAL', 'ELECTRICAL')], max_length=40, null=True)),
                ('Vyear', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('Vusername', models.CharField(max_length=40)),
                ('Vpassword', models.CharField(max_length=40)),
                ('Vmobile_no', models.PositiveBigIntegerField()),
                ('Vemail_id', models.EmailField(max_length=254)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.admin')),
                ('candidate1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted', to='login.candidate')),
                ('candidate2', models.ManyToManyField(related_name='views', to='login.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResults',
            fields=[
                ('w_id', models.IntegerField(primary_key=True, serialize=False)),
                ('w_name', models.CharField(max_length=40)),
                ('w_year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('w_position', models.CharField(choices=[('SECRETARY', 'SECRETARY'), ('ASSISTANT SECRETARY', 'ASSISTANT SECRETARY'), ('PRESIDENT', 'PRESIDENT'), ('VICE PRESIDENT', 'VICE PRESIDENT')], max_length=40)),
                ('w_dept', models.CharField(choices=[('COMPUTER SCIENCE', 'COMPUTER SCIENCE'), ('INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY'), ('ELECTRONICS', 'ELECTRONICS'), ('MECHANICAL', 'MECHANICAL'), ('ELECTRICAL', 'ELECTRICAL')], max_length=40, null=True)),
                ('election', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='login.election')),
            ],
            options={
                'unique_together': {('w_id', 'election')},
            },
        ),
    ]
