# Generated by Django 3.1.3 on 2020-11-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Cemail_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Cpassword',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Cusername',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='e_position',
            field=models.CharField(choices=[('SECRETARY', 'SECRETARY'), ('ASSISTANT SECRETARY', 'ASSISTANT SECRETARY'), ('PRESIDENT', 'PRESIDENT'), ('VICE PRESIDENT', 'VICE PRESIDENT')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='Vemail_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='Vpassword',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='Vusername',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
