# Generated by Django 3.1.3 on 2020-11-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201129_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedCandidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.candidate')),
            ],
        ),
    ]
