# Generated by Django 3.1.3 on 2020-11-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_candidate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotedLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votedcandidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.candidate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.voter')),
            ],
        ),
    ]
