# Generated by Django 3.1.3 on 2020-11-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_winnerlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerlist',
            name='candidates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.candidate'),
        ),
    ]
