# Generated by Django 3.1.3 on 2020-11-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201130_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerlist',
            name='totalvote',
            field=models.IntegerField(),
        ),
    ]
