# Generated by Django 3.1.3 on 2020-12-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20201130_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='candidate2',
        ),
        migrations.DeleteModel(
            name='ElectionResults',
        ),
    ]
