# Generated by Django 3.1.3 on 2020-12-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20201202_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='candidate1',
        ),
    ]
